Service:
 Customer: NTCT IT
 Service_Category: Infrastructure
 Key: IT;All;nGP;Infrastructure;Daily
 Description: Daily Feed of Infrastructure Health checks All Locations
 query_file: nGP_queries/infrastructure/infrastructure_query_daily.yml
 logging: logs/infrastructure_tests.log
 logging_level: INFO
 filename: infrastructure_nGP_Daily_
 date_format: '%Y%m%d_%H%M'
 output_format:
  - customer 
  - location
  - service
  - date
  - infrastructureName
  - normalPercentage
  - degradedPercentage
  - excessivePercentage
  - criticalPercentage
  - noDataPercentage
  - count
  - startTimeMs
  - endTimeMs