# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'github:$(build.buildId)'

steps:
- script: 
docker login mtvaas.azurecr.io -u mtvaas -p lBS15R=rBhF9PSBfCXrZUfuZ5CcXtfRF
docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'
inputs:
  command: 'Push an image'
  containerregistrytype: 'Azure Container Registry'
  azureContainerRegistry: 'mtvaas.azurecr.io'
  imageName: 'mtvaas.azurecr.io/github:$(Build.BuildId)'