Service:
 Customer: Netscout
 Service_Category: Applications
 Key: Netscout;All;nG1;Applications
 Description: Daily Feed of Applications KPIs from nG1
 query_file: nG1_queries/service_applications_daily.xml
 logging: logs/applications_vaaspipe.log
 logging_level: INFO
 filename: applications_nG1_Daily_
 date_format: '%Y%m%d_%H%M'
 output_format:
  - Customer
  - Service
  - Location
  - Date
  - serviceId
  - targetTime
  - failedTransactions
  - totalTransactions
  - responseTime
  - failedPercentage
  - serviceId_String
  - targetTime_String

