Service:
 Customer: NTCT IT
 Service_Category: Applications
 Key: IT;All;nG1;Applications;Monthly
 Description: Monthly Feed of Applications KPIs from nG1
 query_file: nG1_queries/applications/service_applications_monthly.xml
 logging: logs/applications_monthly_vaaspipe.log
 logging_level: INFO
 filename: applications_nG1_Monthly_
 date_format: '%Y%m%d_%H%M'
 output_format:
  - customer
  - service
  - location
  - date
  - totalTransactions
  - responseTime
  - failedTransactions
  - serviceId
  - failedPercentage
  - targetTime
  - serviceId_String
  - targetTime_String
  - successfulTransactions
  - timeOutPercentage
  - requestRetries
  - totalResets
  - timeout
  - totalRetries
  - serverConnectTime
  - serverResets
  - newSessions
  - activeSessions
  - avgConnectTime
  - successfulPercentage
  - avgClientConnectTime
  - serverRetries
  - clientResets
  - clientRetries
  - clientWinSize
  - clientAckRetransmission
  - clientMinWindow
  - serverMinWindow
  - serverAckRetransmission
  - serverAckTime
  - clientAckTime
  - serverWinSize
