Service:
 Customer: NTCT IT
 Service_Category: Applications
 Key: IT;All;nG1;Applications-Errors;Daily
 Description: Daily Feed of Applications Errors from nG1
 query_file: nG1_queries/applications/service_applicationsDrillDown_daily.xml
 logging: logs/applications_vaaspipe.log
 logging_level: INFO
 filename: applications-Errors_nG1_Daily_
 date_format: '%Y%m%d_%H%M'
 output_format:
  - customer
  - service
  - location
  - date
  - appId
  - errorCode
  - messageId
  - targetTime
  - errorCount
  - serviceId
  - appId_String
  - messageId_String
  - targetTime_String
  - serviceId_String