Service:
 Customer: Netscout
 Service_Category: Applications
 Key: PHASE 2;Netscout;All;nG1;Applications;Daily;Drill
 Description: Daily Feed of Applications Drill Down KPIs from nG1
 query_file: nG1_queries/applications/service_applicationsDrillDown_daily.xml
 logging: logs/applications_vaaspipe.log
 logging_level: INFO
 filename: applications_nG1_Daily_Drill_
 date_format: '%Y%m%d_%H%M'
 output_format:
  - Customer
  - Service
  - Location
  - Date
  - appId
  - errorCode
  - messageId
  - targetTime
  - errorCount
  - serviceId
  - appId_String
  - messageId_String
  - targetTime_String
  - serviceId_String