Service:
 Customer: Netscout
 Service_Category: Applications
 Key: PHASE 2;Netscout;All;nG1;Applications;Daily
 Description: Daily Feed of Applications KPIs from nG1
 query_file: nG1_queries/applications/service_applications_daily.xml
 logging: logs/applications_vaaspipe.log
 logging_level: INFO
 filename: applications_nG1_Daily_
 date_format: '%Y%m%d_%H%M'
 output_format:
  - customer
  - service
  - location
  - date
  - totalTransactions
  - responseTime
  - failedTransactions
  - serviceId
  - failedPercentage
  - targetTime
  - serviceId_String
  - targetTime_String